apiVersion: v1
kind: Service
metadata:
  name: db-manager-operator
  namespace: ${DB_MANAGER_OPERATOR_NAMESPACE}
  labels:
    app: db-manager-operator
spec:
  ports:
  - name: api
    port: 443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
---
# To get to the host machine from the VM,
# the IP is 10.0.2.2 (by convention)
# ref: https://stackoverflow.com/questions/9537751/virtualbox-port-forward-from-guest-to-host
apiVersion: v1
kind: Endpoints
metadata:
  name: db-manager-operator
  namespace: ${DB_MANAGER_OPERATOR_NAMESPACE}
  labels:
    app: db-manager-operator
subsets:
- addresses:
  - ip: 10.0.2.2
  ports:
  - name: api
    port: 8443
    protocol: TCP
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.validators.authorization.kubedb.com
  labels:
    app: db-manager-operator
spec:
  insecureSkipTLSVerify: true
  group: validators.authorization.kubedb.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: db-manager-operator
    namespace: ${DB_MANAGER_OPERATOR_NAMESPACE}
  version: v1alpha1
