apiVersion: users.kubedb.com/v1alpha1
#kind: Notifier
kind: MessagingService
metadata:
  name: hipchat-ops-room
spec:
  drive: hipchat
#  notifier: hipchat
  to:
  - ops-alerts
  credentialSecretName: notifier-config